apiVersion: v1
kind: Service
metadata:
  name: resilient-bartender-svc
spec:
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app.kubernetes.io/component: api
    app.kubernetes.io/name: resilient-bartender
  type: NodePort